name: Go

on: [pull_request]

jobs:
  test:
    strategy:
      matrix:
        go:
        - 1.16
        - 1.17
        os:
        - ubuntu-latest
        - [self-hosted, ARM64]

    runs-on: {{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup Go {{ matrix.go }}
      uses: actions/setup-go@v2
      with:
        go-version: {{ matrix.go }}

    - name: Download Dependencies
      run: go mod download

    - name: Test
      run: go test -v ./...
